In [1]:
import pandas as pd
import streamlit as st
import duckdb
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import json
from sklearn.preprocessing import MinMaxScaler
# st.title("🚗 Data Insights" )

In [2]:
def load_data():
    con = duckdb.connect(database=':memory:', read_only=False)
    path=r"C:\Users\Shaaf\Desktop\Data Science\Practice Projects\Transport Planning\Sampled_Data\combined_sampled_data.parquet"
    df = con.execute(f"SELECT * FROM '{path}'").df()
    return df
data = load_data()

In [3]:
data

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-08 12:55:37,2025-01-08 13:23:57,1.0,3.50,1.0,N,166,262,1,23.30,2.50,0.5,5.45,0.0,1.0,32.75,2.5,0.0,0.00
1,2,2025-01-12 15:08:16,2025-01-12 15:16:15,NaN,1.26,NaN,None,41,75,0,13.58,0.00,0.5,3.02,0.0,1.0,18.10,NaN,NaN,0.00
2,2,2025-01-22 10:18:58,2025-01-22 10:32:20,2.0,1.73,1.0,N,164,144,4,13.50,0.00,0.5,0.00,0.0,1.0,18.25,2.5,0.0,0.75
3,2,2025-01-21 19:36:32,2025-01-21 19:46:12,1.0,1.47,1.0,N,107,186,2,10.70,2.50,0.5,0.00,0.0,1.0,17.95,2.5,0.0,0.75
4,2,2025-01-17 14:41:37,2025-01-17 14:47:38,1.0,0.81,1.0,N,75,74,1,7.90,0.00,0.5,2.82,0.0,1.0,12.22,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4023615,1,2025-10-26 21:24:08,2025-10-26 21:28:14,1.0,0.60,1.0,N,48,246,1,5.80,4.25,0.5,2.30,0.0,1.0,13.85,2.5,0.0,0.75
4023616,1,2025-10-04 12:11:26,2025-10-04 12:15:45,1.0,0.80,1.0,N,237,263,2,5.80,2.50,0.5,0.00,0.0,1.0,9.80,2.5,0.0,0.00
4023617,2,2025-10-21 20:24:52,2025-10-21 21:02:30,NaN,6.68,NaN,None,107,238,0,-2.88,0.00,0.5,0.00,0.0,1.0,7.23,NaN,NaN,0.75
4023618,2,2025-10-04 15:15:22,2025-10-04 15:31:20,2.0,3.39,1.0,N,65,255,1,19.10,0.00,0.5,4.12,0.0,1.0,24.72,0.0,0.0,0.00
4023619,1,2025-10-26 17:22:04,2025-10-26 17:42:01,1.0,1.50,99.0,N,41,42,1,18.50,0.00,0.5,0.00,0.0,0.0,19.00,0.0,0.0,0.00

In [4]:
import os

In [5]:
print(os.getcwd())

c:\Users\Shaaf\Desktop\Data Science\Practice Projects\Transport Planning\Trasnport_planning-streamlit

In [6]:
parquet_path = r"C:\Users\Shaaf\Desktop\Data Science\Practice Projects\Transport Planning\Sampled_Data\combined_sampled_data.parquet"

In [7]:
os.path.basename(parquet_path)

'combined_sampled_data.parquet'

In [8]:
from pathlib import Path

In [9]:
project_dir = Path().resolve().parent
data_dir = project_dir/"Data"

In [10]:
project_dir

WindowsPath('C:/Users/Shaaf/Desktop/Data Science/Practice Projects/Transport Planning')

In [11]:
data_dir

WindowsPath('C:/Users/Shaaf/Desktop/Data Science/Practice Projects/Transport Planning/Data')

In [12]:
data_dir.resolve()

WindowsPath('C:/Users/Shaaf/Desktop/Data Science/Practice Projects/Transport Planning/Data')

In [13]:
parquet_files = [
    f for f in os.listdir(data_dir)
    if f.endswith(".parquet") and f.startswith("yellow_tripdata_")
]

In [14]:
parquet_files

['yellow_tripdata_2025-01.parquet',
 'yellow_tripdata_2025-02.parquet',
 'yellow_tripdata_2025-03.parquet',
 'yellow_tripdata_2025-04.parquet',
 'yellow_tripdata_2025-05.parquet',
 'yellow_tripdata_2025-06.parquet',
 'yellow_tripdata_2025-07.parquet',
 'yellow_tripdata_2025-08.parquet',
 'yellow_tripdata_2025-09.parquet',
 'yellow_tripdata_2025-10.parquet']

In [15]:
data_dir

WindowsPath('C:/Users/Shaaf/Desktop/Data Science/Practice Projects/Transport Planning/Data')

In [16]:
loaction_id = pd.read_csv(data_dir/"location_ids.csv")

In [17]:
loaction_id

     LocationID        Borough                     Zone service_zone
0             1            EWR           Newark Airport          EWR
1             2         Queens              Jamaica Bay    Boro Zone
2             3          Bronx  Allerton/Pelham Gardens    Boro Zone
3             4      Manhattan            Alphabet City  Yellow Zone
4             5  Staten Island            Arden Heights    Boro Zone
..          ...            ...                      ...          ...
260         261      Manhattan       World Trade Center  Yellow Zone
261         262      Manhattan           Yorkville East  Yellow Zone
262         263      Manhattan           Yorkville West  Yellow Zone
263         264        Unknown                      NaN          NaN
264         265            NaN           Outside of NYC          NaN

[265 rows x 4 columns]

In [18]:
data.isnull().sum()

VendorID                      0
tpep_pickup_datetime          0
tpep_dropoff_datetime         0
passenger_count          940212
trip_distance                 0
RatecodeID               940212
store_and_fwd_flag       940212
PULocationID                  0
DOLocationID                  0
payment_type                  0
fare_amount                   0
extra                         0
mta_tax                       0
tip_amount                    0
tolls_amount                  0
improvement_surcharge         0
total_amount                  0
congestion_surcharge     940212
Airport_fee              940212
cbd_congestion_fee            0
dtype: int64

In [19]:
df2= data.copy()

In [20]:
loaction_id

     LocationID        Borough                     Zone service_zone
0             1            EWR           Newark Airport          EWR
1             2         Queens              Jamaica Bay    Boro Zone
2             3          Bronx  Allerton/Pelham Gardens    Boro Zone
3             4      Manhattan            Alphabet City  Yellow Zone
4             5  Staten Island            Arden Heights    Boro Zone
..          ...            ...                      ...          ...
260         261      Manhattan       World Trade Center  Yellow Zone
261         262      Manhattan           Yorkville East  Yellow Zone
262         263      Manhattan           Yorkville West  Yellow Zone
263         264        Unknown                      NaN          NaN
264         265            NaN           Outside of NYC          NaN

[265 rows x 4 columns]

In [21]:
df2= pd.merge(df2, loaction_id, left_on="PULocationID",right_on="LocationID", how='left')

In [22]:
df2.shape

(4023620, 24)

In [23]:
940212/4023620

0.23367315999025753

In [24]:
data.shape

(4023620, 20)

In [25]:
df2 = data[data['RatecodeID'].notnull()]

In [26]:
58006/len(data)

0.014416371327312221

In [27]:
df2.dtypes

VendorID                          int32
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int32
DOLocationID                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
cbd_congestion_fee              float64
dtype: object

In [28]:
numeric_data = df2.select_dtypes('number')

In [29]:
numeric_data

,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,1.0,3.50,1.0,166,262,1,23.3,2.50,0.5,5.45,0.0,1.0,32.75,2.5,0.00,0.00
2,2,2.0,1.73,1.0,164,144,4,13.5,0.00,0.5,0.00,0.0,1.0,18.25,2.5,0.00,0.75
3,2,1.0,1.47,1.0,107,186,2,10.7,2.50,0.5,0.00,0.0,1.0,17.95,2.5,0.00,0.75
4,2,1.0,0.81,1.0,75,74,1,7.9,0.00,0.5,2.82,0.0,1.0,12.22,0.0,0.00,0.00
6,2,1.0,0.82,1.0,237,236,1,7.9,0.00,0.5,2.38,0.0,1.0,14.28,2.5,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4023614,2,1.0,15.70,1.0,132,112,1,60.4,1.00,0.5,12.58,0.0,1.0,77.23,0.0,1.75,0.00
4023615,1,1.0,0.60,1.0,48,246,1,5.8,4.25,0.5,2.30,0.0,1.0,13.85,2.5,0.00,0.75
4023616,1,1.0,0.80,1.0,237,263,2,5.8,2.50,0.5,0.00,0.0,1.0,9.80,2.5,0.00,0.00
4023618,2,2.0,3.39,1.0,65,255,1,19.1,0.00,0.5,4.12,0.0,1.0,24.72,0.0,0.00,0.00
4023619,1,1.0,1.50,99.0,41,42,1,18.5,0.00,0.5,0.00,0.0,0.0,19.00,0.0,0.00,0.00

In [30]:
numeric_data.corr()

KeyboardInterrupt:

In [ ]:
df2

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-08 12:55:37,2025-01-08 13:23:57,1.0,3.50,1.0,N,166,262,1,23.3,2.50,0.5,5.45,0.0,1.0,32.75,2.5,0.00,0.00
2,2,2025-01-22 10:18:58,2025-01-22 10:32:20,2.0,1.73,1.0,N,164,144,4,13.5,0.00,0.5,0.00,0.0,1.0,18.25,2.5,0.00,0.75
3,2,2025-01-21 19:36:32,2025-01-21 19:46:12,1.0,1.47,1.0,N,107,186,2,10.7,2.50,0.5,0.00,0.0,1.0,17.95,2.5,0.00,0.75
4,2,2025-01-17 14:41:37,2025-01-17 14:47:38,1.0,0.81,1.0,N,75,74,1,7.9,0.00,0.5,2.82,0.0,1.0,12.22,0.0,0.00,0.00
6,2,2025-01-29 13:54:04,2025-01-29 14:01:13,1.0,0.82,1.0,N,237,236,1,7.9,0.00,0.5,2.38,0.0,1.0,14.28,2.5,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4023614,2,2025-10-16 20:15:13,2025-10-16 20:56:22,1.0,15.70,1.0,N,132,112,1,60.4,1.00,0.5,12.58,0.0,1.0,77.23,0.0,1.75,0.00
4023615,1,2025-10-26 21:24:08,2025-10-26 21:28:14,1.0,0.60,1.0,N,48,246,1,5.8,4.25,0.5,2.30,0.0,1.0,13.85,2.5,0.00,0.75
4023616,1,2025-10-04 12:11:26,2025-10-04 12:15:45,1.0,0.80,1.0,N,237,263,2,5.8,2.50,0.5,0.00,0.0,1.0,9.80,2.5,0.00,0.00
4023618,2,2025-10-04 15:15:22,2025-10-04 15:31:20,2.0,3.39,1.0,N,65,255,1,19.1,0.00,0.5,4.12,0.0,1.0,24.72,0.0,0.00,0.00
4023619,1,2025-10-26 17:22:04,2025-10-26 17:42:01,1.0,1.50,99.0,N,41,42,1,18.5,0.00,0.5,0.00,0.0,0.0,19.00,0.0,0.00,0.00

In [ ]:
dict = {"Newark Airport":2,"JFK Airport":3}

In [ ]:
based_on_drop = {132:3,1:2}

In [ ]:
df2['RatecodeID']=  df2['RatecodeID'].fillna(df2['DOLocationID'].map(based_on_drop)) ##### {"Newark Airport":2,"JFK Airport":3}

C:\Users\Shaaf\AppData\Local\Temp\ipykernel_17760\3695793484.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['RatecodeID']=  df2['RatecodeID'].fillna(df2['DOLocationID'].map(based_on_drop)) ##### {"Newark Airport":2,"JFK Airport":3}

In [ ]:
loaction_id

     LocationID        Borough                     Zone service_zone
0             1            EWR           Newark Airport          EWR
1             2         Queens              Jamaica Bay    Boro Zone
2             3          Bronx  Allerton/Pelham Gardens    Boro Zone
3             4      Manhattan            Alphabet City  Yellow Zone
4             5  Staten Island            Arden Heights    Boro Zone
..          ...            ...                      ...          ...
260         261      Manhattan       World Trade Center  Yellow Zone
261         262      Manhattan           Yorkville East  Yellow Zone
262         263      Manhattan           Yorkville West  Yellow Zone
263         264        Unknown                      NaN          NaN
264         265            NaN           Outside of NYC          NaN

[265 rows x 4 columns]

In [ ]:
df2 = pd.merge(df2,loaction_id, left_on='PULocationID', right_on='LocationID', how='left')

In [ ]:
df2['RatecodeID']=  df2['RatecodeID'].fillna(df2['Zone'].map(dict)) #####{"Newark Airport":2,"JFK Airport":3}

In [ ]:
df2['RatecodeID'].value_counts()

RatecodeID
1.0     2857280
2.0      109728
99.0      58006
5.0       36723
3.0       12120
4.0        9548
6.0           3
Name: count, dtype: int64

In [ ]:
df2.isnull().sum()

VendorID                    0
tpep_pickup_datetime        0
tpep_dropoff_datetime       0
passenger_count             0
trip_distance               0
RatecodeID                  0
store_and_fwd_flag          0
PULocationID                0
DOLocationID                0
payment_type                0
fare_amount                 0
extra                       0
mta_tax                     0
tip_amount                  0
tolls_amount                0
improvement_surcharge       0
total_amount                0
congestion_surcharge        0
Airport_fee                 0
cbd_congestion_fee          0
LocationID                  0
Borough                  1780
Zone                     6661
service_zone             8441
dtype: int64

In [ ]:
df2['RatecodeID'].fillna(1, inplace=True)

C:\Users\Shaaf\AppData\Local\Temp\ipykernel_17760\3733939036.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['RatecodeID'].fillna(1, inplace=True)

In [ ]:
df2.isnull().sum()

VendorID                    0
tpep_pickup_datetime        0
tpep_dropoff_datetime       0
passenger_count             0
trip_distance               0
RatecodeID                  0
store_and_fwd_flag          0
PULocationID                0
DOLocationID                0
payment_type                0
fare_amount                 0
extra                       0
mta_tax                     0
tip_amount                  0
tolls_amount                0
improvement_surcharge       0
total_amount                0
congestion_surcharge        0
Airport_fee                 0
cbd_congestion_fee          0
LocationID                  0
Borough                  1780
Zone                     6661
service_zone             8441
dtype: int64

In [ ]:
df2.shape

(3083408, 24)

In [ ]:
# %matplotlib inline
# sns.boxplot(df2['trip_distance'])

In [ ]:
##trip distance bins

bins= [0, 1, 3, 5, 10, 20, 50,100]

In [ ]:
df2['New_Trip_Bins']= pd.cut(df2['trip_distance'], bins=bins, labels=['0-1','1-3','3-5','5-10','10-20','20-50','50-100'], include_lowest=True)

In [ ]:
df2['New_Trip_Bins'].value_counts()

New_Trip_Bins
1-3       1442844
0-1        800268
3-5        314927
5-10       264872
10-20      229414
20-50       30535
50-100        447
Name: count, dtype: int64

In [ ]:
(447+82)/len(df2)

0.00017156341295086476

In [ ]:
len(df2[df2['trip_distance']>100])

101

In [ ]:
drop_dist = ('20-50','50-100')

In [ ]:
df2

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,LocationID,Borough,Zone,service_zone,New_Trip_Bins
0,1,2025-01-08 12:55:37,2025-01-08 13:23:57,1.0,3.50,1.0,N,166,262,1,...,1.0,32.75,2.5,0.00,0.00,166,Manhattan,Morningside Heights,Boro Zone,3-5
1,2,2025-01-22 10:18:58,2025-01-22 10:32:20,2.0,1.73,1.0,N,164,144,4,...,1.0,18.25,2.5,0.00,0.75,164,Manhattan,Midtown South,Yellow Zone,1-3
2,2,2025-01-21 19:36:32,2025-01-21 19:46:12,1.0,1.47,1.0,N,107,186,2,...,1.0,17.95,2.5,0.00,0.75,107,Manhattan,Gramercy,Yellow Zone,1-3
3,2,2025-01-17 14:41:37,2025-01-17 14:47:38,1.0,0.81,1.0,N,75,74,1,...,1.0,12.22,0.0,0.00,0.00,75,Manhattan,East Harlem South,Boro Zone,0-1
4,2,2025-01-29 13:54:04,2025-01-29 14:01:13,1.0,0.82,1.0,N,237,236,1,...,1.0,14.28,2.5,0.00,0.00,237,Manhattan,Upper East Side South,Yellow Zone,0-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3083403,2,2025-10-16 20:15:13,2025-10-16 20:56:22,1.0,15.70,1.0,N,132,112,1,...,1.0,77.23,0.0,1.75,0.00,132,Queens,JFK Airport,Airports,10-20
3083404,1,2025-10-26 21:24:08,2025-10-26 21:28:14,1.0,0.60,1.0,N,48,246,1,...,1.0,13.85,2.5,0.00,0.75,48,Manhattan,Clinton East,Yellow Zone,0-1
3083405,1,2025-10-04 12:11:26,2025-10-04 12:15:45,1.0,0.80,1.0,N,237,263,2,...,1.0,9.80,2.5,0.00,0.00,237,Manhattan,Upper East Side South,Yellow Zone,0-1
3083406,2,2025-10-04 15:15:22,2025-10-04 15:31:20,2.0,3.39,1.0,N,65,255,1,...,1.0,24.72,0.0,0.00,0.00,65,Brooklyn,Downtown Brooklyn/MetroTech,Boro Zone,3-5
3083407,1,2025-10-26 17:22:04,2025-10-26 17:42:01,1.0,1.50,99.0,N,41,42,1,...,0.0,19.00,0.0,0.00,0.00,41,Manhattan,Central Harlem,Boro Zone,1-3

In [ ]:
df2['New_Trip_Bins'].value_counts()

New_Trip_Bins
1-3       1442844
0-1        800268
3-5        314927
5-10       264872
10-20      229414
20-50       30535
50-100        447
Name: count, dtype: int64

In [ ]:
df2=df2[(df2['New_Trip_Bins']!='20-50') &(df2['New_Trip_Bins']!='50-100')]

In [ ]:
df2.shape

(3052426, 25)

In [ ]:
(len(data[data['RatecodeID']==99])/len(df2))*100

1.9003245287518844

In [ ]:
df2['RatecodeID'].value_counts()

RatecodeID
1.0     2848721
2.0       95919
99.0      56251
5.0       35477
3.0       10657
4.0        5398
6.0           3
Name: count, dtype: int64

In [ ]:
# df2=df2[df2['RatecodeID']!=99]

In [ ]:
10657+5398+3+58006

74064

In [ ]:
df2

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,LocationID,Borough,Zone,service_zone,New_Trip_Bins
0,1,2025-01-08 12:55:37,2025-01-08 13:23:57,1.0,3.50,1.0,N,166,262,1,...,1.0,32.75,2.5,0.00,0.00,166,Manhattan,Morningside Heights,Boro Zone,3-5
1,2,2025-01-22 10:18:58,2025-01-22 10:32:20,2.0,1.73,1.0,N,164,144,4,...,1.0,18.25,2.5,0.00,0.75,164,Manhattan,Midtown South,Yellow Zone,1-3
2,2,2025-01-21 19:36:32,2025-01-21 19:46:12,1.0,1.47,1.0,N,107,186,2,...,1.0,17.95,2.5,0.00,0.75,107,Manhattan,Gramercy,Yellow Zone,1-3
3,2,2025-01-17 14:41:37,2025-01-17 14:47:38,1.0,0.81,1.0,N,75,74,1,...,1.0,12.22,0.0,0.00,0.00,75,Manhattan,East Harlem South,Boro Zone,0-1
4,2,2025-01-29 13:54:04,2025-01-29 14:01:13,1.0,0.82,1.0,N,237,236,1,...,1.0,14.28,2.5,0.00,0.00,237,Manhattan,Upper East Side South,Yellow Zone,0-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3083403,2,2025-10-16 20:15:13,2025-10-16 20:56:22,1.0,15.70,1.0,N,132,112,1,...,1.0,77.23,0.0,1.75,0.00,132,Queens,JFK Airport,Airports,10-20
3083404,1,2025-10-26 21:24:08,2025-10-26 21:28:14,1.0,0.60,1.0,N,48,246,1,...,1.0,13.85,2.5,0.00,0.75,48,Manhattan,Clinton East,Yellow Zone,0-1
3083405,1,2025-10-04 12:11:26,2025-10-04 12:15:45,1.0,0.80,1.0,N,237,263,2,...,1.0,9.80,2.5,0.00,0.00,237,Manhattan,Upper East Side South,Yellow Zone,0-1
3083406,2,2025-10-04 15:15:22,2025-10-04 15:31:20,2.0,3.39,1.0,N,65,255,1,...,1.0,24.72,0.0,0.00,0.00,65,Brooklyn,Downtown Brooklyn/MetroTech,Boro Zone,3-5
3083407,1,2025-10-26 17:22:04,2025-10-26 17:42:01,1.0,1.50,99.0,N,41,42,1,...,0.0,19.00,0.0,0.00,0.00,41,Manhattan,Central Harlem,Boro Zone,1-3

In [ ]:
df2.shape

(3052426, 25)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split,StratifiedShuffleSplit
import os
import logging
from pathlib import Path
import duckdb
# Setting up logging
log_dir = 'logs'
os.makedirs(log_dir, exist_ok=True)

project_dir = Path().resolve().parent
data_dir = project_dir/"Data"

# logging configuration
logger = logging.getLogger('Data_Processing')
logger.setLevel(logging.DEBUG) 

console_handler = logging.StreamHandler()
console_handler.setLevel(logging.DEBUG)  

log_file_path = os.path.join(log_dir, 'Data_Processing.log') 
file_handler = logging.FileHandler(log_file_path)
file_handler.setLevel(logging.DEBUG)  

formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
console_handler.setFormatter(formatter)
file_handler.setFormatter(formatter)

logger.addHandler(console_handler)
logger.addHandler(file_handler)

logger.info("Beginning the data processing")

def load_data():
    try:
        con = duckdb.connect(database=':memory:', read_only=False)
        path=data_dir/"combined_sampled_data.parquet"
        df = con.execute(f"SELECT * FROM '{path}'").df()
        logger.info(f"Loaded data with shape: {df.shape}")
        return df
    except Exception as e:
        logger.error(f"Error loading data: {e}")
        raise


def data_processing(data):
    try:
        logger.info(f"Beginning the data_processing function")
        loaction_id = pd.read_csv(data_dir/"location_ids.csv") ## Getting the names of the Locations ID's
        data = pd.merge(data, loaction_id, left_on="PULocationID",right_on="LocationID", how='left') ## merging loactions
        logger.info(f"data shape before processing {data.shape}")
        ##there are NAN values in Ratecode filling using below logic, the details were found on the google
        pickup_location = {"Newark Airport":2,"JFK Airport":3} 
        based_on_drop_location = {132:3,1:2}
        data['RatecodeID']=  data['RatecodeID'].fillna(data['DOLocationID'].map(based_on_drop_location))
        data['RatecodeID']=  data['RatecodeID'].fillna(data['Zone'].map(pickup_location)) #####{"Newark Airport":2,"JFK Airport":3}
        ##Rest all the RateCodeID becomes 1
        data['RatecodeID'].fillna(1, inplace=True)

        ##Creating bins for the distance travelled
        bins= [0, 1, 3, 5, 10, 20, 50]
        data=data[data['trip_distance']<=50].copy() ## found about 500 values where the distance is beyond 50miles, dropping them as outlier
        data['Trip Distance Bins'] = pd.cut(data['trip_distance'], bins=bins,labels=['0-1','1-3','3-5','5-10','10-20','20-50'], include_lowest=True)
        logger.info(f"data shape before processing {data.shape}")
        return data
        
    except Exception as e:
        logger.error(f"Error while processing the data{e}")

# data = load_data()

2026-07-07 19:45:48,774 - Data_Processing - INFO - Beginning the data processing
2026-07-07 19:45:48,774 - Data_Processing - INFO - Beginning the data processing
2026-07-07 19:45:48,774 - Data_Processing - INFO - Beginning the data processing
2026-07-07 19:45:48,774 - Data_Processing - INFO - Beginning the data processing
2026-07-07 19:45:48,774 - Data_Processing - INFO - Beginning the data processing

In [ ]:
data = load_data()

2026-07-07 19:46:34,573 - Data_Processing - INFO - Loaded data with shape: (4023620, 20)
2026-07-07 19:46:34,573 - Data_Processing - INFO - Loaded data with shape: (4023620, 20)
2026-07-07 19:46:34,573 - Data_Processing - INFO - Loaded data with shape: (4023620, 20)
2026-07-07 19:46:34,573 - Data_Processing - INFO - Loaded data with shape: (4023620, 20)
2026-07-07 19:46:34,573 - Data_Processing - INFO - Loaded data with shape: (4023620, 20)

In [ ]:
data = data_processing(data)

2026-07-07 19:46:52,914 - Data_Processing - INFO - Beginning the data_processing function
2026-07-07 19:46:52,914 - Data_Processing - INFO - Beginning the data_processing function
2026-07-07 19:46:52,914 - Data_Processing - INFO - Beginning the data_processing function
2026-07-07 19:46:52,914 - Data_Processing - INFO - Beginning the data_processing function
2026-07-07 19:46:52,914 - Data_Processing - INFO - Beginning the data_processing function
2026-07-07 19:46:53,715 - Data_Processing - INFO - data shape before processing (4023620, 24)
2026-07-07 19:46:53,715 - Data_Processing - INFO - data shape before processing (4023620, 24)
2026-07-07 19:46:53,715 - Data_Processing - INFO - data shape before processing (4023620, 24)
2026-07-07 19:46:53,715 - Data_Processing - INFO - data shape before processing (4023620, 24)
2026-07-07 19:46:53,715 - Data_Processing - INFO - data shape before processing (4023620, 24)
C:\Users\Shaaf\AppData\Local\Temp\ipykernel_17760\2010307046.py:58: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['RatecodeID'].fillna(1, inplace=True)
2026-07-07 19:46:56,811 - Data_Processing - INFO - data shape before processing (4022854, 25)
2026-07-07 19:46:56,811 - Data_Processing - INFO - data shape before processing (4022854, 25)
2026-07-07 19:46:56,811 - Data_Processing - INFO - data shape before processing (4022854, 25)
2026-07-07 19:46:56,811 - Data_Processing - INFO - data shape before processing (4022854, 25)
2026-07-07 19:46:56,811 - Data_Processing - INFO - data shape before processing (4022854, 25)

In [ ]:
data

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,LocationID,Borough,Zone,service_zone,Trip Distance Bins
0,1,2025-01-08 12:55:37,2025-01-08 13:23:57,1.0,3.50,1.0,N,166,262,1,...,1.0,32.75,2.5,0.0,0.00,166,Manhattan,Morningside Heights,Boro Zone,3-5
1,2,2025-01-12 15:08:16,2025-01-12 15:16:15,NaN,1.26,1.0,None,41,75,0,...,1.0,18.10,NaN,NaN,0.00,41,Manhattan,Central Harlem,Boro Zone,1-3
2,2,2025-01-22 10:18:58,2025-01-22 10:32:20,2.0,1.73,1.0,N,164,144,4,...,1.0,18.25,2.5,0.0,0.75,164,Manhattan,Midtown South,Yellow Zone,1-3
3,2,2025-01-21 19:36:32,2025-01-21 19:46:12,1.0,1.47,1.0,N,107,186,2,...,1.0,17.95,2.5,0.0,0.75,107,Manhattan,Gramercy,Yellow Zone,1-3
4,2,2025-01-17 14:41:37,2025-01-17 14:47:38,1.0,0.81,1.0,N,75,74,1,...,1.0,12.22,0.0,0.0,0.00,75,Manhattan,East Harlem South,Boro Zone,0-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4023615,1,2025-10-26 21:24:08,2025-10-26 21:28:14,1.0,0.60,1.0,N,48,246,1,...,1.0,13.85,2.5,0.0,0.75,48,Manhattan,Clinton East,Yellow Zone,0-1
4023616,1,2025-10-04 12:11:26,2025-10-04 12:15:45,1.0,0.80,1.0,N,237,263,2,...,1.0,9.80,2.5,0.0,0.00,237,Manhattan,Upper East Side South,Yellow Zone,0-1
4023617,2,2025-10-21 20:24:52,2025-10-21 21:02:30,NaN,6.68,1.0,None,107,238,0,...,1.0,7.23,NaN,NaN,0.75,107,Manhattan,Gramercy,Yellow Zone,5-10
4023618,2,2025-10-04 15:15:22,2025-10-04 15:31:20,2.0,3.39,1.0,N,65,255,1,...,1.0,24.72,0.0,0.0,0.00,65,Brooklyn,Downtown Brooklyn/MetroTech,Boro Zone,3-5
4023619,1,2025-10-26 17:22:04,2025-10-26 17:42:01,1.0,1.50,99.0,N,41,42,1,...,0.0,19.00,0.0,0.0,0.00,41,Manhattan,Central Harlem,Boro Zone,1-3

In [ ]:
data.isnull().sum()

VendorID                      0
tpep_pickup_datetime          0
tpep_dropoff_datetime         0
passenger_count          939994
trip_distance                 0
RatecodeID                    0
store_and_fwd_flag       939994
PULocationID                  0
DOLocationID                  0
payment_type                  0
fare_amount                   0
extra                         0
mta_tax                       0
tip_amount                    0
tolls_amount                  0
improvement_surcharge         0
total_amount                  0
congestion_surcharge     939994
Airport_fee              939994
cbd_congestion_fee            0
LocationID                    0
Borough                    1808
Zone                       6858
service_zone               8666
Trip Distance Bins            0
dtype: int64

In [ ]:
numeric_data

,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,1.0,3.50,1.0,166,262,1,23.3,2.50,0.5,5.45,0.0,1.0,32.75,2.5,0.00,0.00
2,2,2.0,1.73,1.0,164,144,4,13.5,0.00,0.5,0.00,0.0,1.0,18.25,2.5,0.00,0.75
3,2,1.0,1.47,1.0,107,186,2,10.7,2.50,0.5,0.00,0.0,1.0,17.95,2.5,0.00,0.75
4,2,1.0,0.81,1.0,75,74,1,7.9,0.00,0.5,2.82,0.0,1.0,12.22,0.0,0.00,0.00
6,2,1.0,0.82,1.0,237,236,1,7.9,0.00,0.5,2.38,0.0,1.0,14.28,2.5,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4023614,2,1.0,15.70,1.0,132,112,1,60.4,1.00,0.5,12.58,0.0,1.0,77.23,0.0,1.75,0.00
4023615,1,1.0,0.60,1.0,48,246,1,5.8,4.25,0.5,2.30,0.0,1.0,13.85,2.5,0.00,0.75
4023616,1,1.0,0.80,1.0,237,263,2,5.8,2.50,0.5,0.00,0.0,1.0,9.80,2.5,0.00,0.00
4023618,2,2.0,3.39,1.0,65,255,1,19.1,0.00,0.5,4.12,0.0,1.0,24.72,0.0,0.00,0.00
4023619,1,1.0,1.50,99.0,41,42,1,18.5,0.00,0.5,0.00,0.0,0.0,19.00,0.0,0.00,0.00

In [ ]:
correlations = numeric_data.corrwith(numeric_data['passenger_count'])
print(correlations)

VendorID                 0.062444
passenger_count          1.000000
trip_distance            0.003404
RatecodeID              -0.052875
PULocationID            -0.013169
DOLocationID            -0.008419
payment_type             0.034298
fare_amount              0.047779
extra                   -0.062390
mta_tax                 -0.044931
tip_amount               0.026703
tolls_amount             0.033314
improvement_surcharge    0.002137
total_amount             0.046078
congestion_surcharge    -0.007357
Airport_fee              0.028209
cbd_congestion_fee       0.012346
dtype: float64

In [ ]:
import os

# Option A: Using os.path.join (Safest across all operating systems)
full_path = os.path.join(data_dir, "passenger-count.csv")
(data.groupby(['Zone', 'passenger_count'])['passenger_count'].sum().to_frame()).to_csv(full_path)

# Option B: Clean f-string approach (If data_dir doesn't end with a slash)
# (data.groupby(['Zone', 'passenger_count'])['passenger_count'].sum().to_frame()).to_csv(f"{data_dir}/passenger-count.csv")

In [ ]:
{
    'Upper East Side South': {1: 1, 2: 2},
    'JFK Airport': {1: 1, 2: 2},
}

In [ ]:
data['passenger_count'].fillna(1, inplace=True)

C:\Users\Shaaf\AppData\Local\Temp\ipykernel_17760\4016041303.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['passenger_count'].fillna(1, inplace=True)

In [ ]:
data.isnull().sum()

VendorID                      0
tpep_pickup_datetime          0
tpep_dropoff_datetime         0
passenger_count               0
trip_distance                 0
RatecodeID                    0
store_and_fwd_flag       939994
PULocationID                  0
DOLocationID                  0
payment_type                  0
fare_amount                   0
extra                         0
mta_tax                       0
tip_amount                    0
tolls_amount                  0
improvement_surcharge         0
total_amount                  0
congestion_surcharge     939994
Airport_fee              939994
cbd_congestion_fee            0
LocationID                    0
Borough                    1808
Zone                       6858
service_zone               8666
Trip Distance Bins            0
dtype: int64

In [ ]:
data['passenger_count'].value_counts()

passenger_count
1.0    3383750
2.0     426267
3.0      98934
4.0      67554
0.0      22347
5.0      15182
6.0       8803
8.0          7
9.0          7
7.0          3
Name: count, dtype: int64

In [ ]:
data['congestion_surcharge'].value_counts()

congestion_surcharge
 2.5    2750185
 0.0     276446
-2.5      56227
 1.0          2
Name: count, dtype: int64

In [ ]:
full_path_2 = os.path.join(data_dir, "surge_charge_count.csv")

In [ ]:
data.groupby(['Zone','congestion_surcharge'])['congestion_surcharge'].count().to_frame().to_csv(full_path_2)

In [ ]:
data['store_and_fwd_flag'].value_counts()

store_and_fwd_flag
N    3072812
Y      10048
Name: count, dtype: int64

In [36]:
import pandas as pd
from sklearn.model_selection import train_test_split,StratifiedShuffleSplit
import os
import logging
from pathlib import Path
import duckdb
# Setting up logging
log_dir = 'logs'
os.makedirs(log_dir, exist_ok=True)

project_dir = Path().resolve().parent
data_dir = project_dir/"Data"

# logging configuration
logger = logging.getLogger('Data_Processing')
logger.setLevel(logging.DEBUG) 

console_handler = logging.StreamHandler()
console_handler.setLevel(logging.DEBUG)  

log_file_path = os.path.join(log_dir, 'Data_Processing.log') 
file_handler = logging.FileHandler(log_file_path)
file_handler.setLevel(logging.DEBUG)  

formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
console_handler.setFormatter(formatter)
file_handler.setFormatter(formatter)

logger.addHandler(console_handler)
logger.addHandler(file_handler)

logger.info("Beginning the data processing")

def load_data():
    try:
        con = duckdb.connect(database=':memory:', read_only=False)
        path=os.path.join(data_dir, "combined_sampled_data.parquet")
        df = con.execute(f"SELECT * FROM '{path}'").df()
        logger.info(f"Loaded data with shape: {df.shape}")
        return df
    except Exception as e:
        logger.error(f"Error loading data: {e}")
        raise


def data_processing(data):
    try:
        logger.info(f"Beginnng the data_processing function")
        loaction_id = pd.read_csv(data_dir/"location_ids.csv") ## Getting the names of the Locations ID's
        data = pd.merge(data, loaction_id, left_on="PULocationID",right_on="LocationID", how='left') ## merging loactions
        logger.info(f"data shape before processing {data.shape}")
        ##there are NAN values in Ratecode filling using below logic, the details were found on the google
        pickup_location = {"Newark Airport":2,"JFK Airport":3} 
        based_on_drop_location = {132:3,1:2}
        data['RatecodeID']=  data['RatecodeID'].fillna(data['DOLocationID'].map(based_on_drop_location))
        data['RatecodeID']=  data['RatecodeID'].fillna(data['Zone'].map(pickup_location)) #####{"Newark Airport":2,"JFK Airport":3}
        ##Rest all the RateCodeID becomes 1
        data['RatecodeID'].fillna(1, inplace=True)

        ##Creating bins for the distance travelled
        bins= [0, 1, 3, 5, 10, 20, 50]
        data=data[data['trip_distance']<=50].copy() ## found about 500 values where the distance is beyond 50miles, dropping them as outlier
        data['Trip Distance Bins'] = pd.cut(data['trip_distance'], 
                                            bins=bins,labels=['0-1','1-3','3-5','5-10','10-20','20-50'], include_lowest=True)
        
        ##There are NAN values in passenger counts,Most of the values are 1 based on analysis and review
        data['passenger_count'].fillna(1, inplace=True)

        ##there are outliers with 6, 7 and 8 passenger counts
        data =data[data['passenger_count']<=5]
        data['congestion_surcharge'].fillna(0, inplace=True)
        data['store_and_fwd_flag'].fillna('N', inplace=True)
        data['Airport_fee'].fillna(0, inplace=True)
        logger.info(f"data shape before processing {data.shape}")
        return data
        
    except Exception as e:
        logger.error(f"Error while processing the data{e}")

data = load_data()
data= data_processing(data)

2026-07-08 12:53:22,566 - Data_Processing - INFO - Beginning the data processing
2026-07-08 12:53:22,566 - Data_Processing - INFO - Beginning the data processing
2026-07-08 12:53:22,566 - Data_Processing - INFO - Beginning the data processing
2026-07-08 12:53:22,566 - Data_Processing - INFO - Beginning the data processing
2026-07-08 12:53:22,566 - Data_Processing - INFO - Beginning the data processing
2026-07-08 12:53:22,566 - Data_Processing - INFO - Beginning the data processing
2026-07-08 12:53:24,924 - Data_Processing - INFO - Loaded data with shape: (4023620, 20)
2026-07-08 12:53:24,924 - Data_Processing - INFO - Loaded data with shape: (4023620, 20)
2026-07-08 12:53:24,924 - Data_Processing - INFO - Loaded data with shape: (4023620, 20)
2026-07-08 12:53:24,924 - Data_Processing - INFO - Loaded data with shape: (4023620, 20)
2026-07-08 12:53:24,924 - Data_Processing - INFO - Loaded data with shape: (4023620, 20)
2026-07-08 12:53:24,924 - Data_Processing - INFO - Loaded data with shape: (4023620, 20)
2026-07-08 12:53:24,935 - Data_Processing - INFO - Beginnng the data_processing function
2026-07-08 12:53:24,935 - Data_Processing - INFO - Beginnng the data_processing function
2026-07-08 12:53:24,935 - Data_Processing - INFO - Beginnng the data_processing function
2026-07-08 12:53:24,935 - Data_Processing - INFO - Beginnng the data_processing function
2026-07-08 12:53:24,935 - Data_Processing - INFO - Beginnng the data_processing function
2026-07-08 12:53:24,935 - Data_Processing - INFO - Beginnng the data_processing function
2026-07-08 12:53:25,783 - Data_Processing - INFO - data shape before processing (4023620, 24)
2026-07-08 12:53:25,783 - Data_Processing - INFO - data shape before processing (4023620, 24)
2026-07-08 12:53:25,783 - Data_Processing - INFO - data shape before processing (4023620, 24)
2026-07-08 12:53:25,783 - Data_Processing - INFO - data shape before processing (4023620, 24)
2026-07-08 12:53:25,783 - Data_Processing - INFO - data shape before processing (4023620, 24)
2026-07-08 12:53:25,783 - Data_Processing - INFO - data shape before processing (4023620, 24)
C:\Users\Shaaf\AppData\Local\Temp\ipykernel_27092\2650557222.py:58: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['RatecodeID'].fillna(1, inplace=True)
C:\Users\Shaaf\AppData\Local\Temp\ipykernel_27092\2650557222.py:67: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['passenger_count'].fillna(1, inplace=True)
C:\Users\Shaaf\AppData\Local\Temp\ipykernel_27092\2650557222.py:71: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['congestion_surcharge'].fillna(0, inplace=True)
C:\Users\Shaaf\AppData\Local\Temp\ipykernel_27092\2650557222.py:72: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['store_and_fwd_flag'].fillna('N', inplace=True)
C:\Users\Shaaf\AppData\Local\Temp\ipykernel_27092\2650557222.py:73: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Airport_fee'].fillna(0, inplace=True)
2026-07-08 12:53:29,145 - Data_Processing - INFO - data shape before processing (4014034, 25)
2026-07-08 12:53:29,145 - Data_Processing - INFO - data shape before processing (4014034, 25)
2026-07-08 12:53:29,145 - Data_Processing - INFO - data shape before processing (4014034, 25)
2026-07-08 12:53:29,145 - Data_Processing - INFO - data shape before processing (4014034, 25)
2026-07-08 12:53:29,145 - Data_Processing - INFO - data shape before processing (4014034, 25)
2026-07-08 12:53:29,145 - Data_Processing - INFO - data shape before processing (4014034, 25)

In [39]:
data.dtypes

VendorID                          int32
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int32
DOLocationID                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
cbd_congestion_fee              float64
LocationID                        int64
Borough                          object
Zone                             object
service_zone                     object
Trip Distance Bins             category
dtype: object

In [41]:
path=os.path.join(data_dir, "combined_sampled_data.parquet")

In [42]:
path

'C:\\Users\\Shaaf\\Desktop\\Data Science\\Practice Projects\\Transport Planning\\Data\\combined_sampled_data.parquet'